# Generated by Django 2.1.4 on 2019-01-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0003_auto_20181204_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='picture',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='users',
            name='picture_thumb',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
