# Generated by Django 2.1.4 on 2019-01-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0004_auto_20190106_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default=None, max_length=255)),
                ('lname', models.CharField(default=None, max_length=255)),
                ('email', models.CharField(default=None, max_length=255, unique=True)),
                ('password', models.CharField(default=None, max_length=255)),
                ('picture', models.CharField(default=None, max_length=500)),
                ('picture_thumb', models.CharField(default=None, max_length=500)),
                ('position_id', models.IntegerField(default=0)),
                ('region_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('msisdn', models.CharField(default=None, max_length=255)),
                ('device_uid', models.CharField(default='JESUS', max_length=255)),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='voter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default=None, max_length=255)),
                ('lname', models.CharField(default=None, max_length=255)),
                ('email', models.CharField(default=None, max_length=255, unique=True)),
                ('password', models.CharField(default=None, max_length=255)),
                ('region_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('msisdn', models.CharField(default=None, max_length=255)),
                ('device_uid', models.CharField(default='JESUS', max_length=255)),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.RenameField(
            model_name='vote_token',
            old_name='user_id',
            new_name='voter_id',
        ),
    ]
