# Generated by Django 2.1.4 on 2019-01-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0006_auto_20190111_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
