# Generated by Django 2.1.4 on 2019-01-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0007_candidate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='position_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
