# Generated by Django 2.1.4 on 2019-01-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0009_auto_20190112_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='status',
        ),
        migrations.AddField(
            model_name='election',
            name='activate',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
