# Generated by Django 2.1.4 on 2019-01-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0010_auto_20190113_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='activate',
        ),
        migrations.AddField(
            model_name='election',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
